#app-flask deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-flask
  name: app-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-flask
  template:
    metadata:
      labels:
        app: app-flask
    spec:
      containers:
        - image: europe-west1-docker.pkg.dev/taibi-samira/reg-flask/app_flask:2b461fd75d7c7c7d3a37a30feae7721eac641a72
          name: app-flask
          ports:
            - containerPort: 5011
              name: app-flask
---
#app-flask service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-flask
  name: app-flask
spec:
  type: LoadBalancer
  ports:
  - name: "app-flask"
    port: 5011
    targetPort: 5011
  selector:
    app: app-flask
